#define IDM_PASSWORD_TEXT     100
#define IDM_PASSWORD_TO_TEXT	101
#define IDM_NEW_PASSWORD_NAME_TEXT 102
#define IDM_PASSWORD_RENAME   103
#define IDM_PASSWORD_CANCEL   104
#define IDM_PASSWORD_INCORRECT 105
#define IDM_PASSWORD_HELP 168
