@echo off
rem set _autofile=%autofile%
rem set autofile=%dosdir%\orig.bat
if "%1"=="test" goto init
if not "%1"=="" goto loop
goto begin

:init
shift
call postset CRYNWRX WATTCPX CTMOUSEX GRUBX ASPIX DOSLFNX PERUSEX SCSIX USBDOSX VIAX EMACSX SETEDITX
call postset VIMRTX VIM16X VIM32X OPENGEMX FBCX FPASCALX OWATCOMX PACIFICX XHARBORX ARACHNEX
call postset LYNXX LNXSMALX LYNXXEX PMAILX DOGX FPROTX BSPLASHX
goto end

:loop
if "%1"=="" goto end
FDPKG /DISPLAY %1 > NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK %1
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE
shift
goto loop



:begin
FDPKG /DISPLAY crynwrx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK crynwrx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE crynwrx
FDPKG /DISPLAY wattcpx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK wattcpx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE wattcpx
FDPKG /DISPLAY ctmousex >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK ctmousex
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE ctmousex
FDPKG /DISPLAY grubx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK grubx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE grubx
FDPKG /DISPLAY aspix >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK aspix
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE aspix
FDPKG /DISPLAY doslfnx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK doslfnx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE doslfnx
FDPKG /DISPLAY perusex >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK perusex
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE perusex
FDPKG /DISPLAY scsix >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK scsix
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE scsix
FDPKG /DISPLAY usbdosx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK usbdosx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE usbdosx
FDPKG /DISPLAY viax >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK viax
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE viax
FDPKG /DISPLAY emacsx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK emacsx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE emacsx
FDPKG /DISPLAY seteditx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK seteditx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE seteditx
FDPKG /DISPLAY vimrtx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK vimrtx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE vimrtx
FDPKG /DISPLAY vim16x >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK vim16x
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE vim16x
FDPKG /DISPLAY vim32x >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK vim32x
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE vim32x
FDPKG /DISPLAY opengemx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK opengemx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE opengemx
FDPKG /DISPLAY fbcx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK fbcx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE fbcx
FDPKG /DISPLAY fpascalx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK fpascalx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE fpascalx
FDPKG /DISPLAY owatcomx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK owatcomx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE owatcomx
FDPKG /DISPLAY pacificx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK pacificx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE pacificx
FDPKG /DISPLAY xharborx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK xharborx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE xharborx
FDPKG /DISPLAY arachnex >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK arachnex
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE arachnex
FDPKG /DISPLAY lynxx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK lynxx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE lynxx
FDPKG /DISPLAY lnxsmalx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK lnxsmalx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE lnxsmalx
FDPKG /DISPLAY lynxexx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK lynxexx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE lynxexx
FDPKG /DISPLAY pmailx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK pmailx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE pmailx
FDPKG /DISPLAY dogx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK dogx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE dogx
FDPKG /DISPLAY fprotx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK fprotx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE fprotx
FDPKG /DISPLAY bsplashx >NUL
IF NOT ERRORLEVEL 1 FDPKG /CHECK bsplashx
IF NOT ERRORLEVEL 1 FDPKG /CONFIGURE bsplashx
rem set autofile=%_autofile%
rem set _autofile=
goto end

:end